### Load balancing paradis runs
rank0 = {('CommSendGhosts', 'ParadisStep'): 1822974,
 ('CommSendRemesh', 'ParadisStep'): 35428,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 2244904,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2521484,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1723510,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 5077906,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 5923326,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 1270866,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 99214,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 4880,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 89200,
 ('Migrate', 'ParadisStep'): 193786}

rank1 = {('CommSendGhosts', 'ParadisStep'): 1856568,
 ('CommSendRemesh', 'ParadisStep'): 5586,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 967144,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2016422,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1784416,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 5031902,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 6178428,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 882920,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 123966,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 14536,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 86598,
 ('Migrate', 'ParadisStep'): 128950}

rank2 ={('CommSendGhosts', 'ParadisStep'): 1190682,
 ('CommSendRemesh', 'ParadisStep'): 54650,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 1843282,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2544130,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1988726,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 4239480,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 4248284,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 1116970,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 184972,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 77474,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 52260,
 ('Migrate', 'ParadisStep'): 145170}

rank3 = {('CommSendGhosts', 'ParadisStep'): 1917194,
 ('CommSendRemesh', 'ParadisStep'): 866106,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 1510286,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2723916,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1731438,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 5017238,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 6749348,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 1125892,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 222844,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 200720,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 32826,
 ('Migrate', 'ParadisStep'): 207500}

rank4 = {('CommSendGhosts', 'ParadisStep'): 1706590,
 ('CommSendRemesh', 'ParadisStep'): 774904,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 1088650,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2390156,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1385462,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 5565720,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 5958204,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 986550,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 137948,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 97356,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 185830,
 ('Migrate', 'ParadisStep'): 173766}

rank5 = {('CommSendGhosts', 'ParadisStep'): 2284264,
 ('CommSendRemesh', 'ParadisStep'): 140,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 1693814,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2268976,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1800224,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 4858372,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 7532402,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 1163150,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 105144,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 47822,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 123762,
 ('Migrate', 'ParadisStep'): 153418}

rank6 = {('CommSendGhosts', 'ParadisStep'): 1710870,
 ('CommSendRemesh', 'ParadisStep'): 960314,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 1163270,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2101812,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1357514,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 5444596,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 5981410,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 1342360,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 135482,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 89628,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 59878,
 ('Migrate', 'ParadisStep'): 101820}

rank7 = {('CommSendGhosts', 'ParadisStep'): 1915404,
 ('CommSendRemesh', 'ParadisStep'): 12732,
 ('CommSendRemesh', 'Remesh', 'ParadisStep'): 1961680,
 ('CommSendSecondaryGhosts', 'CommSendGhosts', 'ParadisStep'): 2382998,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'ParadisStep'): 1481390,
 ('CommSendSegForces', 'LocalSegForces', 'NodeForce', 'TrapezoidIntegrator', 'ParadisStep'): 5500360,
 ('CommSendVelocity', 'TrapezoidIntegrator', 'ParadisStep'): 6594046,
 ('DistributeTagMaps', 'Migrate', 'ParadisStep'): 1132102,
 ('FMCommDownPass', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 101778,
 ('FMCommUpPass', 'CellCharge', 'ParadisStep'): 45452,
 ('FMDistTaylorExp', 'FMSetTaylorExpansions', 'CellCharge', 'ParadisStep'): 100436,
 ('Migrate', 'ParadisStep'): 137902}
